/**/slam_toolbox:  # 名前空間を含めたノード名
  ros__parameters:
    use_sim_time: True
    autostart: True
    odom_frame: robot_4dw/odom
    base_frame: robot_4dw/base_footprint
    scan_topic: /robot_4dw/scan
    map_frame: robot_4dw/map
    mode: mapping
    # map_file_name: "/home/ubuntu/git/amr/gazebo/amr_robot_launcher/map"
    map_start_at_dock: True
    dimensions: 2
