/**/slam_toolbox:  # 名前空間を含めたノード名
  ros__parameters:
    autostart: true
    odom_frame: robot_4dw/odom
    base_frame: robot_4dw/base_footprint
    scan_topic: /robot_4dw/scan
    map_frame: robot_4dw/map
    use_sim_time: true
    mode: mapping
